CREATE TABLE TRUCK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plate VARCHAR(255) NOT NULL
);
CREATE TABLE POSITION_RECORD (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    truck_id BIGINT NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    timestamp BIGINT NOT NULL,
    FOREIGN KEY (truck_id) REFERENCES TRUCK(id) ON DELETE CASCADE
);