-- src/test/resources/schema.sql
DROP TABLE IF EXISTS POSITION_RECORD;
DROP TABLE IF EXISTS TRUCK;

CREATE TABLE TRUCK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plate VARCHAR(255) NOT NULL
);

CREATE TABLE POSITION_RECORD (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    truck_id BIGINT NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    timestamp BIGINT NOT NULL,
    FOREIGN KEY (truck_id) REFERENCES TRUCK(id) ON DELETE CASCADE
);

CREATE TABLE "USER"
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    roles      VARCHAR(255) NOT NULL
);